// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DealSe.Domain.Models
{
    public partial class City
    {
        public City()
        {
            Area = new HashSet<Area>();
        }

        [Key]
        public int CityId { get; set; }
        public int StateId { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public bool Active { get; set; }

        [ForeignKey(nameof(StateId))]
        [InverseProperty("City")]
        public virtual State State { get; set; }
        [InverseProperty("City")]
        public virtual ICollection<Area> Area { get; set; }
    }
}