// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DealSe.Domain.Models
{
    public partial class StoreType
    {
        public StoreType()
        {
            Store = new HashSet<Store>();
            SuggestedOffer = new HashSet<SuggestedOffer>();
        }

        [Key]
        public int StoreTypeId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        public bool Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedDate { get; set; }

        [InverseProperty("StoreType")]
        public virtual ICollection<Store> Store { get; set; }
        [InverseProperty("StoreType")]
        public virtual ICollection<SuggestedOffer> SuggestedOffer { get; set; }
    }
}