// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DealSe.Data.Models
{
    public partial class Country
    {
        public Country()
        {
            State = new HashSet<State>();
        }

        [Key]
        public int CountryId { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public bool Active { get; set; }

        [InverseProperty("Country")]
        public virtual ICollection<State> State { get; set; }
    }
}