// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DealSe.Data.Models
{
    public partial class Offer
    {
        public Offer()
        {
            OfferBanner = new HashSet<OfferBanner>();
            UserUsedOffer = new HashSet<UserUsedOffer>();
        }

        [Key]
        public int OfferId { get; set; }
        public int StoreId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        [Required]
        [StringLength(500)]
        public string SortDescription { get; set; }
        public string LongDescription { get; set; }
        public string TermsAndConditions { get; set; }
        public bool LimitedTimeOffer { get; set; }
        public bool Approved { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public bool Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedDate { get; set; }

        [ForeignKey(nameof(StoreId))]
        [InverseProperty("Offer")]
        public virtual Store Store { get; set; }
        [InverseProperty("Offer")]
        public virtual ICollection<OfferBanner> OfferBanner { get; set; }
        [InverseProperty("Offer")]
        public virtual ICollection<UserUsedOffer> UserUsedOffer { get; set; }
    }
}