// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DealSe.Data.Models
{
    public partial class OfferBanner
    {
        [Key]
        public int OfferBannerId { get; set; }
        public int OfferId { get; set; }
        [Required]
        [StringLength(50)]
        public string Image { get; set; }
        public bool Approved { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        public bool Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedDate { get; set; }

        [ForeignKey(nameof(OfferId))]
        [InverseProperty("OfferBanner")]
        public virtual Offer Offer { get; set; }
    }
}