// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DealSe.Data.Models
{
    public partial class State
    {
        public State()
        {
            City = new HashSet<City>();
        }

        [Key]
        public int StateId { get; set; }
        public int CountryId { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public bool Active { get; set; }

        [ForeignKey(nameof(CountryId))]
        [InverseProperty("State")]
        public virtual Country Country { get; set; }
        [InverseProperty("State")]
        public virtual ICollection<City> City { get; set; }
    }
}