// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DealSe.Data.Models
{
    public partial class StoreSuggestedOffer
    {
        [Key]
        public int StoreSuggestedOfferId { get; set; }
        public int StoreId { get; set; }
        public int SuggestedOfferId { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        public bool Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedDate { get; set; }
        [StringLength(10)]
        public string OfferImage { get; set; }

        [ForeignKey(nameof(StoreId))]
        [InverseProperty("StoreSuggestedOffer")]
        public virtual Store Store { get; set; }
        [ForeignKey(nameof(SuggestedOfferId))]
        [InverseProperty("StoreSuggestedOffer")]
        public virtual SuggestedOffer SuggestedOffer { get; set; }
    }
}