// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DealSe.Data.Models
{
    public partial class SuggestedOffer
    {
        public SuggestedOffer()
        {
            StoreSuggestedOffer = new HashSet<StoreSuggestedOffer>();
        }

        [Key]
        public int SuggestedOfferId { get; set; }
        public int StoreTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Image { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        public string SortDescription { get; set; }
        public string LongDescription { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedDate { get; set; }
        public bool Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedDate { get; set; }
        [StringLength(10)]
        public string OfferImage { get; set; }

        [ForeignKey(nameof(StoreTypeId))]
        [InverseProperty("SuggestedOffer")]
        public virtual StoreType StoreType { get; set; }
        [InverseProperty("SuggestedOffer")]
        public virtual ICollection<StoreSuggestedOffer> StoreSuggestedOffer { get; set; }
    }
}